name: 部署前端项目

# 只有master分支发生push主分支或pull_request关闭后事件时，才会触发workflow
on:
  push:
    branches:
      # 你的主分支名
      - master
  pull_request:
    branches:
      # 你的主分支名
      - master
    types:
      - closed
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v3

      # 安装Node10
      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 上传阿里云
      - name: copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          password: ${{ secrets.SERVER_SSH_PASS }}
          command_timeout: 10m
          source: "./dist/*"
          rm: true
          target: "/www/wwwroot/xlApi"
